# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: adb5927883103626c67ef22fd3bc57ec5b0380ab740edaba2406ee9fa46a1a2aec48fb89e9aeee1fa95cd7336d9aa7eabde1b31c59361d1bec00fc806e1709bf

test:
  secret_key_base: c2b49b42e4e316f9dd7d3002615b7a4e52f9e4e257a75740290345160b9c0a00034f022730625925a24f5a435715e5531468f6025bee25c97e862eb5fabbd38a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
